sudo apt update -y;
sudo apt upgrade -y;
sudo apt install python3 -y;
sudo apt install python3-pip python3-pygame -y;
pip3 install PyOpenGL PyOpenGL_accelerate;
sudo apt install ubuntu-desktop mesa-utils -y;
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -;
sudo apt-get install apt-transport-https;
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list;
sudo apt update -y;
sudo apt install sublime-text -y;
DISPLAY=:0 /opt/sublime_text/sublime_text ../multiplayerGame;
export DISPLAY=localhost:0;
